trigger:
- master  # You can specify the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # You can choose an appropriate agent image

steps:
- script: |
    cd pipelines-java  # Navigate to the directory containing your pom.xml
    mvn clean package
  displayName: 'Maven Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'pipelines-java/target'  # Adjust the path to your built JAR/WAR file
    ArtifactName: 'drop'
    publishLocation: 'Container'
