trigger:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: 'Install .NET Framework 4.x'

  - script: |
      cd dotnet-framework
      dotnet restore $(solution)
    displayName: 'Restore NuGet Packages'

  - script: |
      cd dotnet-framework
      dotnet build $(solution) --configuration $(buildConfiguration)
    displayName: 'Build the project'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/dnfw' # Update the path as per your project structure
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'
