name: dotnetcore.ci

trigger:
  branches:
    include:
      - dotnetcore-pipeline
    exclude:
      - main
  batch: true

variables:
  buildConfigurations: 'Release'
  vmImageName: 'windows-latest'

pool:
  vmImage: $(vmImageName) # Use the variable for VM image

stages:
- stage: BuildAndPublish
  jobs:
  - job: Build
    variables:
      dotnetVersion: '6.0.x' # Define a job-specific variable
    
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        version: $(dotnetVersion)
        installationPath: $(Agent.ToolsDirectory)/dotnet
    
    - script: |
        find . -type f -name '*.csproj' | while read csproj; do
          echo "Building project $csproj"
          dotnet build "$csproj" --configuration $(buildConfigurations)
        done
      displayName: 'Build'
    
    - script: |
        find . -type f -name '*.csproj' | while read csproj; do
          echo "Publishing project $csproj"
          dotnet publish "$csproj" --configuration $(buildConfigurations) --output $(Build.ArtifactStagingDirectory)
        done
      displayName: 'Publish'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish'
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: "mstest"
