name: dotnetcore.ci

trigger:
  branches:
    include:
      - dotnetcore-pipeline
    exclude:
      - main
  batch: true
pool:
  vmImage: 'windows-latest'
variables:
  buildConfigurations: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true
- task: UseDotNet@2
  displayName: 'set dotnet core version'
  inputs:
    version: '6.0.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfigurations)'


