name: dotnetcore.ci

trigger:
  branches:
    include:
      - dotnetcore-pipeline
    exclude:
      - main
  batch: true

variables:
  buildConfigurations: 'Release'
  vmImageName: 'windows-latest'
  dotnetVersion: '6.0.x' # Define .NET SDK version as a variable

pool:
  vmImage: $(vmImageName) # Use the variable for VM image

parameters:
  - name: applicationPath
    type: string
    default: '**/*.csproj'
    displayName: 'Application Path' # Path to the application project file (e.g., **/*.csproj)

stages:
- stage: BuildAndPublish
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        version: $(dotnetVersion) # Use the .NET SDK version variable

    - script: |
        dotnet build --configuration $(buildConfigurations) --no-restore ${{ parameters.applicationPath }}
      displayName: 'Build'
  
  - job: Publish
    dependsOn: Build
    
    steps:
    - script: |
        dotnet publish --configuration $(buildConfigurations) --no-build --output $(Build.ArtifactStagingDirectory) ${{ parameters.applicationPath }}
      displayName: 'Generate Binaries'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish'
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: "mstest"
