name: dotnetcore.ci

parameters:
- name: applicationPath
  type: string
  default: '**/*.csproj'
  displayName: 'Application Path'

trigger:
  branches:
    include:
      - dotnetcore-pipeline
    exclude:
      - main

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '6.0.x' # Specify the desired .NET version here

pool:
  vmImage: 'windows-latest'

stages:
- stage: BuildAndPublish
  jobs:
  - job: BuildAndPublishJob
    displayName: 'Build and Publish'
    steps:
    - checkout: self

    # Check if the desired .NET version is already cached; if not, install and cache it.
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      inputs:
        version: $(dotnetVersion)
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - script: |
        dotnet --version
        echo "Application Path: ${{parameters.applicationPath}}"
        dotnet build --configuration $(buildConfiguration) "${{ parameters.applicationPath}}"
      displayName: 'Build'
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
