pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd python
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

- script: |
    cd python
    # Build your Flask application (e.g., create database tables, compile assets)
    python app.py
  displayName: 'Build Flask Application'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: 'python/artifacts'  # Specify the path to your build artifacts
    ArtifactName: 'flask-app'  # Choose a name for the published artifact
