pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd python
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python app.py
  displayName: 'Install Python Dependencies'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Specify the path to your build artifacts
    ArtifactName: 'flask-app'  # Choose a name for the published artifact
