trigger:
- nodejs

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    pwd
    ls
    cd nodejs
    npm install
    npm run build
  displayName: 'npm install'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       nodejs/src/*
       nodejs/public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: drop
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: pipeline
    displayName: 'Publish npm artifact'

